name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker registry
      run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/ecrews/weather/server:$GITHUB_SHA
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/ecrews/weather/server:$GITHUB_SHA
